more

diff --git a/packages/contracts/Makefile b/packages/contracts/Makefile
--- a/packages/contracts/Makefile
+++ b/packages/contracts/Makefile
@@ -3,21 +3,23 @@
 include .env
 
 
-simulateDeployment: 
+deploy-framework-simulate: 
 	forge script FactoryDeploy --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) --slow  -vvvv
 
-deployBlax:
-	forge script DeployHere --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) --slow --verify --broadcast --etherscan-api-key $(ETHERSCAN_API_KEY) --verifier $(VERIFIER) -vvvv
+deploy-framework:
+	forge script FactoryDeploy --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) --broadcast --slow -vvvv
+
+framework-store-json:
+	@if [ -z "$(chain-id)" ]; then \
+		echo "Error: chain id is not set. Please pass it as 'make chain-id=<value> framework-store-json'."; \
+		exit 1; \
+	fi
+	npx ts-node scripts/store-deployments.ts $(chain-id) $$(cat deployed_contracts_temp.json)
 
 deploy-repos:
+	@if [ -z "$(pluginrepofactory)" ]; then \
+		echo "Error: pluginrepofactory is not set. Please pass it as 'make pluginrepofactory=<value> ReposDeployment'."; \
+		exit 1; \
+	fi
 	
-
-t:
-	forge script blax --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) --broadcast --slow --verify --etherscan-api-key $(ETHERSCAN_API_KEY) --verifier $(VERIFIER) -vvvv
-
-o:
-	forge script DeployHere --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) --slow --verify --etherscan-api-key $(ETHERSCAN_API_KEY) --verifier $(VERIFIER) -vvvv
-
-
-h:
-	forge script Helper --chain $(CHAIN) --rpc-url $(NETWORK_RPC_URL) -vvvv
+	@bash bash.sh $(pluginrepofactory) $(fork)
